title: My Blog
description: A minimal blog
author: Armaan

# Build settings
remote_theme: heiswayi/thinkspace
markdown: kramdown

plugins:
  - jekyll-remote-theme

# Permalink structure
permalink: /:title/

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
