# Site settings
title_left: "ar"
title_right: "maan"
description: "personal blog"
url: https://armaansarkar.github.io
baseurl: "/blog"

# Build settings
permalink: /:title/
markdown: kramdown

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed

# Author settings
author:
  name: "Armaan"

# Show future posts
future: true

# navbar pages
navbar:
  - slug: about
    title: About

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
