title: armaan
description: personal blog
author: Armaan

# Build settings
markdown: kramdown

# Show future posts (timezone issues)
future: true

# Permalink structure
permalink: /:title/

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
